- .github/workflows/ci.yml
> ci: change ci file

- src/generator/packagejson.js
- src/templates/data/repository/postgres/repository.ejs
- src/templates/infra/api/graphql/inputs.ejs
- src/templates/infra/api/graphql/mutations.ejs
- src/templates/infra/api/graphql/queries.ejs
- src/templates/infra/api/graphql/types.ejs
- src/templates/infra/api/rest/index.ejs
Fixes #
1. fix herbs dependencies
> fix: fix herbs dependencies

- src/generator/packagejson.js
Fixes #
1. set version fixed into thrid part dependencies
> set version fixed into thrid part dependencies

- __tests__/cli-integration.test.js
- package-lock.json
- package.json
- src/generator/index.js
- src/generator/packagejson.js
- src/generator/src/config/index.js
- src/generator/src/database/connection.js
- src/generator/src/database/migrations/migrations.js
- src/generator/src/database/repositories/repositories.js
- src/generator/src/domain/entities.js
- src/generator/src/domain/errors.js
- src/generator/src/domain/useCases.js
- src/generator/src/index.js
- src/generator/src/infra/graphql.js
- src/generator/src/infra/rest.js
- src/generator/src/infra/server.js
removed the standard envs from package.json
issue #17
> fix(lint): fix lint configuration

- CHANGELOG.md
- __tests__/cli-integration.test.js
- src/generators/new/packagejson.js
implementation of the bug opened here #29
> fix: infra generate dependencies

- src/templates/infra/api/graphql/index.ejs
> fix: disable introspection when is production

- .eslintrc.json
- package-lock.json
- package.json
- src/generators/new/domain/useCasesTests.js
- src/generators/new/packagejson.js
Add eslint to code and ci. Also refac code in the usecase tests generation
Fixes #
1. add eslint to code
> fix: add eslint to code

- src/generators/new/infra/database/repositories/repositories.js
Fixes #
fix: generating repositories of new entities with the update command - #50
> fix: generating repositories of new entities with the update command

- src/templates/package.json.ejs
> fix: package.json generation using initial project setup options

- package.json
- src/generators/src/packagejson.js
> fix: update knex dependecy

- package-lock.json
- package.json
- src/generators/src/packagejson.js
> fix: fix package lock

- package-lock.json
- package.json
- src/generators/src/packagejson.js
- src/tests/postgres.test.js
> ci: update semantic release version

- package-lock.json
- package.json
- src/commands/herbs.js
- src/commands/new.js
- src/generators/check-version.js
- src/generators/src/packagejson.js
Fixes #114 
1. Now, after a herbs new command, if an update of cli is available, a console information shows up
> feat: show update version when new version is available 

- package-lock.json
- src/generators/src/infra/database/migrations/migrations.js
I didn't open an issue for this because I fixed it when I got the problem.
basically, we don't must create migrations for mongo, so, I just avoid it when we have a mongo config in the project.
> fix: ignore migration for mongo database

- src/generators/src/infra/git.js
- src/tests/git.test.js
- src/tests/packagejson.test.js
- src/tests/postgres.test.js
In the project setup, if the developer chooses to configure version control, the existence of the GIT installation is verified. If it is not installed, it is informed that the GIT was not found and the project is created without versioning.
Fixes #110
> fix: check if git is installed in the operating system

- src/templates/domain/useCases/create.ejs
- src/templates/domain/useCases/update.ejs
Change create and update usecases' request to use request.from() feature
#139
> refactor(create and update usecases): Entity schema to Request schema

- src/generators/src/infra/git.js
Fixes https://github.com/herbsjs/herbs-cli/issues/152
1. Change the order of git commands
> Fix error when try to create a project in linux

- package.json
- src/commands/spec.js
Fixes https://github.com/herbsjs/herbs-cli/issues/175
When I try to run to run unit tests, I get this error at terminal: 
Run npm run test at terminal
> fix bug in running test

- .github/workflows/cd.yml
> test: branch rule with semantic-release on CD

- .github/workflows/cd.yml
> test: semantic rule branch adding no fast-forward

- .github/workflows/cd.yml
> test: new token admin to semantic-release

- .github/workflows/cd.yml
> test: persist-credentials

- package-lock.json
> build(package-lock): update dependencies

- src/generators/src/packagejson.js
- src/templates/domain/useCases/create.ejs
- src/templates/domain/useCases/delete.ejs
- src/templates/domain/useCases/update.ejs
> Revert "Updated version of herbsjs and glues"
